apiVersion: v1
kind: Config
current-context: k8s
clusters:
- name: apiserver
  cluster:
    server: https://$MASTER:6443
    certificate-authority: /etc/kubernetes/ssl/ca.pem
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/$HOSTNAME.pem
    client-key:         /etc/kubernetes/ssl/$HOSTNAME-key.pem
contexts:
  - name: k8s
    context:
      cluster: apiserver
      user: kubelet

